### ISSUE TITLE
Home redesign

### ISSUE THREAD

**Issue by emalorenzo** [coderhood-dev/coderhood-old#53]
![image](https://user-images.githubusercontent.com/10750168/91751019-75ad3d00-eb9a-11ea-8832-a715c86a9eda.png)

ask @SantyLorenzo for the image

**Comment by SantyLorenzo-zz** [comment]
[5 SCENE.zip](https://github.com/coderhooddevs/coderhood/files/5152460/5.SCENE.zip)
@emamasonn here is the svg image for the home page.
